### PR TITLE
Support latest Tensorflow/Keras

### PR DESCRIPTION
**Pull request by innat**
Currently, it supports `tf 2.7` only. But it can be used for `tf >= 2.6`.

### CODE REVIEW

**Comment by innat** [comment]
@muellerdo

**Review by muellerdo — APPROVED** [review]
- setup.py is enhanced through this contribution as intended -> more dynamic 
- requirements.txt should be a momentum status of a functional development environment, so we should keep the version fixation. Added a commit to fix this as well as updated some dependencies

**Comment by muellerdo** [comment]
Depending the setup.py vs requirements.py issue, I refer to the excellent comment of AndreasT in the StackOverflow post:
> requirements.txt:
This helps you to set up your development environment.
...
setup.py:
This helps you to create packages that you can redistribute.

Summarized, setup.py should be more dynamic like in your pull request and requirements.txt should be a momentum status or freeze.

Sources:
- https://stackoverflow.com/questions/43658870/requirements-txt-vs-setup-py
- https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/

**Comment by muellerdo** [comment]
Switched base to dev branch, rerun CI jobs.

**Comment by muellerdo** [comment]
All checks are fine.
Merging.

Thanks for the PR @innat ! :)

**Pull request merged**
