### PR TITLE
Xai visualizer update - split 2

### PR DESCRIPTION
**Pull request by Deathlymad**

### CODE REVIEW

**Comment by muellerdo** [comment]
Update copyright to 2022.

Do we have any unittesting for this?

**Comment by Deathlymad** [comment]
now we do

**Comment by Deathlymad** [comment]
nopt sure about the error, it works my end and the API defines the function thats supposibly doesn't exist:
https://matplotlib.org/3.5.0/api/figure_api.html#matplotlib.figure.FigureBase.supxlabel

**Comment by Deathlymad** [comment]
Dennis noted, that this error may be related tto a version mismatch. so would it be a problem to update matplotlib?

**Comment by muellerdo** [comment]
I don't see anything against updating matplotlib dependencies.

Could you provide a commit for requirements & setup?

**Review by muellerdo — APPROVED** [review]

**Pull request merged**
