### PR TITLE
Multi-Path architecture proposal

### PR DESCRIPTION
**Pull request by jumutc**
Please consider the latest [MDPI paper](https://www.mdpi.com/1424-8220/22/3/990) and the actual implementation.

### CODE REVIEW

**Comment by jumutc** [comment]
@muellerdo I guess some guidelines for Multi-Path architecture usage are needed as well. As stated in the paper all paths should have coherent strides given in `self.feature_maps`.

**Comment by muellerdo** [comment]
Hello @jumutc,

thanks for your great contributions to this repo, as always! :)

Novel architectures are always welcomed and congratulations to your publication.

I have switched the target to the dev branch and added a copyright header as well as a reference to your paper in the code.

> @muellerdo I guess some guidelines for Multi-Path architecture usage are needed as well. As stated in the paper all paths should have coherent strides given in self.feature_maps.

If needed, could you add a note of this in the class doc string (between line 43 and 44)?

**Review by muellerdo — APPROVED** [review]
Approved. Ready for merging.

@jumutc, is more documentation needed?

**Comment by jumutc** [comment]
@muellerdo added clarifying comments to the docstring. Should I put something to Wiki?

**Comment by muellerdo** [comment]
@jumutc perfect! 

> Should I put something to Wiki?

Not needed. I will just copy & paste the class doc-string to the wiki.
If you want to add more to it just let me know^^

**Comment by jumutc** [comment]
@muellerdo all is set then! Thanks for a prompt review! Me and my team will contribute more as we keep on solving some challenging problems in the medical image segmentation.

**Comment by muellerdo** [comment]
Added documentation to wiki.

@jumutc, perfect and happy to hear!
Good luck on further studies!

**Review by muellerdo — APPROVED** [review]
Reviewed doc

**Comment by jumutc** [comment]
@muellerdo maybe Wiki should be corrected a bit as naming/description is incorrect:
"The MultiRes variant of the popular U-Net architecture.
It is an improved version of the standard U-Net and contains some small modifications to improve upon the already state-of-the-art U-Net model." I would change for:
"The Multi-Path variant of the popular "plain" U-Net architecture.
It is an improved version of the "plain" U-Net and contains a few modifications to improve upon the already state-of-the-art U-Net model."

**Pull request merged**
